name: CI
 
on:
  push:
    branches: [ main ]
 
env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_IMAGE_NAME: nodejs-aws-process-movement
 
jobs:
  docker:
    name: CI Images
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME:$GITHUB_RUN_NUMBER .
    - name: Login to Docker Hub
      run: docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the docker image
      run: docker push $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME:$GITHUB_RUN_NUMBER
 